import { GoogleGenAI, Type } from "@google/genai";

// Represents the structure of content generated by the AI
export interface GeneratedContent {
    title: string;
    description: string;
    tags: string;
}

// Per coding guidelines, API key must be from process.env.API_KEY.
const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_API_KEY as string });

export const generateContent = async (topic: string): Promise<GeneratedContent> => {
    const prompt = `
    You are a social media marketing expert specializing in creating viral video content. 
    Based on the topic "${topic}", generate the following for TikTok, YouTube, and Instagram. 
    The tone should be engaging and optimized for maximum reach.

    1. A catchy, short title (max 60 characters).
    2. An engaging description (max 250 characters), including 3-5 relevant hashtags.
    3. A comma-separated list of 10-15 relevant and trending tags.

    Ensure the output is a valid JSON object.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        title: {
                            type: Type.STRING,
                            description: "The catchy video title."
                        },
                        description: {
                            type: Type.STRING,
                            description: "The engaging video description with hashtags."
                        },
                        tags: {
                            type: Type.STRING,
                            description: "A comma-separated string of relevant tags."
                        }
                    },
                    required: ["title", "description", "tags"]
                },
            },
        });
        
        const jsonText = response.text?.trim();
        if (!jsonText) {
          throw new Error("AI response is empty.");
        }
        const parsedContent = JSON.parse(jsonText) as GeneratedContent;
        
        if (!parsedContent.title || !parsedContent.description || !parsedContent.tags) {
          throw new Error("AI response is missing required fields.");
        }

        return parsedContent;

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate content from AI. Please check your API key and try again.");
    }
};
