name: Check Concept Schedules

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs every hour at the beginning of the hour
    - cron: '0 * * * *'

jobs:
  check-schedules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run schedule check script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: npx ts-node scripts/check-schedules.ts
